### PR TITLE
updated TZDB to 2019c

### PR DESCRIPTION
**Pull request by lemberh**
Updated TZDB to 2019c - two version
changelog - https://data.iana.org/time-zones/tzdb/NEWS

### CODE REVIEW

**Comment by JakeWharton** [comment]
Thanks for the PR, but for the safety of consumers I only update the tzdb from threetenbp myself once it has landed upstream. If you want, you can submit the update to threetenbp and then once it's merged and released I'll pick it up here and issue a new release.

**Comment by douglasiacovelli** [comment]
Hey Jake, they've just released a new version with the 2019c database (https://github.com/ThreeTen/threetenbp/releases/tag/v1.4.1).

Could you please update ThreeTenABP as well? Thank you

**Comment by JakeWharton** [comment]
Yep I saw. Will get it out this week.

**Comment by JakeWharton** [comment]
Released 1.2.2

**Pull request closed without merging**
