### PR TITLE
Lowered minSdkVersion from 15 to 8

### PR DESCRIPTION
**Pull request by ChristianBecker**

### CODE REVIEW

**Comment by JakeWharton** [comment]
8 is Java 5 and thus not supported.

**Comment by ChristianBecker** [comment]
Is minSdk 14 acceptable?

**Comment by JakeWharton** [comment]
Do you have a large percentage of users on API 14? Every device that shipped with API 14 received an update to API 15.

**Comment by ChristianBecker** [comment]
Fair enough. I'm going to close this.

**Pull request closed without merging**
