### PR TITLE
updated version usage of the original repo

### PR DESCRIPTION
**Pull request by AndroidDeveloperLB**

### CODE REVIEW

**Comment by MyDogTom** [comment]
time-zone data was updated [in 1.3.5](http://www.threeten.org/threetenbp/changes-report.html)
I would say, you have to update `TZDB.dat` in same way as it was done in #32

**Comment by AndroidDeveloperLB** [comment]
ok here.

**Comment by AndroidDeveloperLB** [comment]
What is this.
Has it failed even now?

**Comment by partounian** [comment]
Looks to me like the travis config needs to be updated, any chance you can take a look @JakeWharton ?

**Comment by AndroidDeveloperLB** [comment]
So it still doesn't work well?
How come?
:(

**Comment by JakeWharton** [comment]
Rebase on master.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton What's wrong?
Is it ok or not?

**Comment by JakeWharton** [comment]
The build is broken. Rebase on master.

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton I don't understand what you mean. Is it possible to fix this, and update to latest version?

**Comment by AndroidDeveloperLB** [comment]
@JakeWharton Why closed? Updated?

**Comment by partounian** [comment]
@AndroidDeveloperLB I believe he updated with another PR.

**Comment by AndroidDeveloperLB** [comment]
@partounian But the website says it's still version 1.0.5

**Pull request closed without merging**
