### PR TITLE
Disable BuildConfig generation.

### PR DESCRIPTION
**Pull request by vanniktech**

### CODE REVIEW

**Comment by vanniktech** [comment]
Seems like the Travis CI script needs an update:

```
$ echo no | android create avd --force -n test -t android-15 --abi armeabi-v7a
Error: Target id is not valid. Use 'android list targets' to get the target ids.
```

**Comment by JakeWharton** [comment]
I'll take a PR for that. Heads down on Other Stuff™.

**Comment by vanniktech** [comment]
Done in #75

**Comment by vanniktech** [comment]
This is green now.

**Pull request merged**
