### PR TITLE
Init library via content provider

### PR DESCRIPTION
**Pull request by mr-archano**
### Scope:

At the moment the library needs to load the timezone database via [`AndroidThreeTen.init(Context)`](https://github.com/JakeWharton/ThreeTenABP/blob/master/threetenabp/src/main/java/com/jakewharton/threetenabp/AndroidThreeTen.java#L15). From a consumer point of view would be good to find a less intrusive way to achieve the same goal.
### Considerations/Implementation details:

This PR introduces a custom `ContentProvider` that will initialise the library in its `onCreate()` method, where it's safe to use the `Context` to perform the same operations previously in the  application `onCreate()`. This means no code is necessary anymore for consumers of the library, given the `ContentProvider` declaration will be correctly injected in the app manifest.
As a consequence `AndroidThreeTen.init(Context)` has been deprecated but not removed, to avoid the introduction of a breaking change for current adopters.

> **NOTE:** The README has not been changed yet because not sure this change will be accepted. Can do as part of this PR though.

### CODE REVIEW

**Comment by mr-archano** [comment]
@JakeWharton did you get any chance to take a look at this yet?

**Comment by jaredsburrows** [comment]
I say this is a suggestion or opinion. Do not change the API. 

This is just a library, let the developers decide whether or not to use an `Application` or `ContentProvider`.

**Comment by dlew** [comment]
Won't this run into the same problem that other ContentProvider-based initializers do, which is that it initializes it once per process (even when the process may not care about it at all)?

**Comment by jonasfa** [comment]
It would be great if the maintainers reconsidered and merged this. Since `AssetsZoneRulesInitializer` was introduced, this approach postpones the actual initialization until the process actually uses zone rules.

May be relevant, this was published a few months after this PR: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html

**Pull request closed without merging**
